apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: githubsource-openstack-health
spec:
  eventTypes:
  - pull_request
  - push
  - pull_request_review
  - pull_request_review_comment
  ownerAndRepository: "afrittoli/openstack-health"
  accessToken:
    secretKeyRef:
      name: githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: githubsecret
      key: secretToken
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: githubchannel
