apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: health-frontend
  labels:
    app: health
    component: frontend
    tag: __TAG__
spec:
  runLatest:
    configuration:
      build:
        apiVersion: tekton.dev/v1alpha1
        kind: TaskRun
        metadata:
          labels:
            app: health
            component: frontend
            tag: __TAG__
        spec:
          taskRef:
            name: source-to-image
          trigger:
            type: manual
          inputs:
            resources:
              - name: workspace
                resourceRef:
                  name: __GIT_RESOURCE_NAME__
            params:
              - name: pathToContext
                value: .
              - name: pathToDockerFile
                value: images/frontend/Dockerfile
              - name: imageTag
                value: __TAG__                
          outputs:
            resources:
              - name: builtImage
                resourceRef:
                  name: __IMAGE_RESOURCE_NAME__
      revisionTemplate:  # template for building Revision
        spec:
          container:
            image: registry.ng.bluemix.net/andreaf/health-frontend:__TAG__
            imagePullPolicy: Always
            env:
              - name: API_URL
                value: http://health-api.dev.af-health.sjc03.containers.appdomain.cloud/
            ports:
              - name: http1
                containerPort: 80
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /
            readinessProbe:
              httpGet:
                path: /
